SELECT * FROM psyque.post;

update post set texto = '<p style="text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:14px">A sa&uacute;de mental n&atilde;o &eacute; um fen&ocirc;meno isolado; ela est&aacute; intrinsecamente ligada &agrave;s intera&ccedil;&otilde;es humanas e &agrave; din&acirc;mica das comunidades. Nesse contexto, a empatia surge como uma for&ccedil;a poderosa na promo&ccedil;&atilde;o de ambientes mais saud&aacute;veis e solid&aacute;rios. A empatia vai al&eacute;m da simples compreens&atilde;o das emo&ccedil;&otilde;es alheias; ela envolve a capacidade de se colocar no lugar do outro, compartilhando suas alegrias e dores.</span></span></p>
<p style="text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:14px">Ao cultivar a empatia, criamos conex&otilde;es mais profundas e genu&iacute;nas. A escuta ativa, a compreens&atilde;o das experi&ecirc;ncias alheias e a oferta de suporte emocional tornam-se pr&aacute;ticas cotidianas, reduzindo o estigma em torno das quest&otilde;es de sa&uacute;de mental. Quando as pessoas se sentem compreendidas e apoiadas, &eacute; mais prov&aacute;vel que busquem ajuda quando necess&aacute;rio, promovendo a preven&ccedil;&atilde;o e o tratamento precoce de problemas mentais.</span></span></p>
<p style="text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:14px">Al&eacute;m disso, a empatia estende-se &agrave; constru&ccedil;&atilde;o de sociedades mais inclusivas e justas. Ao reconhecer e respeitar as diferentes jornadas e desafios enfrentados por cada indiv&iacute;duo, criamos um ambiente que valoriza a diversidade e promove a aceita&ccedil;&atilde;o incondicional.</span></span></p>
<p style="text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:14px">Portanto, a empatia n&atilde;o &eacute; apenas uma qualidade individual, mas uma for&ccedil;a transformadora que molda a sa&uacute;de mental coletiva. Ao incorporar a empatia em nossa cultura e intera&ccedil;&otilde;es di&aacute;rias, constru&iacute;mos uma base s&oacute;lida para a promo&ccedil;&atilde;o do bem-estar emocional em n&iacute;veis individuais e comunit&aacute;rios.</span></span></p>
' where id = 3;

update post set texto = '<p style="text-align:justify"><span style="font-size:16px"><span style="font-family:Arial,Helvetica,sans-serif">Em meio &agrave;s complexidades da vida, a resili&ecirc;ncia emerge como uma qualidade fundamental para preservar e promover a sa&uacute;de mental. A resili&ecirc;ncia n&atilde;o implica na aus&ecirc;ncia de desafios, mas na capacidade de enfrent&aacute;-los, aprender com as experi&ecirc;ncias adversas e adaptar-se de maneira saud&aacute;vel. &Eacute; um processo cont&iacute;nuo de crescimento pessoal e enfrentamento positivo diante das dificuldades.</span></span></p>

<p style="text-align:justify"><span style="font-size:16px"><span style="font-family:Arial,Helvetica,sans-serif">Desenvolver a resili&ecirc;ncia requer uma combina&ccedil;&atilde;o de fatores, incluindo a busca por apoio social, o cultivo de pensamentos positivos e a pr&aacute;tica regular de autorreflex&atilde;o. O suporte social desempenha um papel crucial, pois compartilhar experi&ecirc;ncias com amigos, familiares ou profissionais pode fornecer perspectivas valiosas e fortalecer os la&ccedil;os emocionais.</span></span></p>

<p style="text-align:justify"><span style="font-size:16px"><span style="font-family:Arial,Helvetica,sans-serif">Al&eacute;m disso, a resili&ecirc;ncia envolve a capacidade de regular as emo&ccedil;&otilde;es e manter uma vis&atilde;o otimista mesmo diante das adversidades. Isso n&atilde;o significa ignorar a dor ou o sofrimento, mas sim encontrar maneiras construtivas de lidar com esses sentimentos, transformando-os em oportunidades de crescimento pessoal.</span></span></p>

<p style="text-align:justify"><span style="font-size:16px"><span style="font-family:Arial,Helvetica,sans-serif">Ao incorporar a resili&ecirc;ncia em nossa vida cotidiana, constru&iacute;mos uma base s&oacute;lida para enfrentar os altos e baixos inevit&aacute;veis da exist&ecirc;ncia. Essa mentalidade resiliente n&atilde;o apenas fortalece a sa&uacute;de mental individual, mas tamb&eacute;m contribui para a forma&ccedil;&atilde;o de comunidades mais adapt&aacute;veis e solid&aacute;rias.</span></span></p>
'
where id = 2;

update post set textp = '<p style="text-align:justify"><span style="font-size:16px">A sa&uacute;de mental &eacute; um campo vasto e complexo que abrange n&atilde;o apenas a aus&ecirc;ncia de doen&ccedil;as mentais, mas tamb&eacute;m o estado de bem-estar psicol&oacute;gico e emocional. Dentro desse contexto, o autoconhecimento emerge como uma ferramenta crucial para promover e manter uma sa&uacute;de mental s&oacute;lida. Conhecer a si mesmo vai al&eacute;m da mera consci&ecirc;ncia de caracter&iacute;sticas superficiais; envolve uma explora&ccedil;&atilde;o profunda de emo&ccedil;&otilde;es, pensamentos, valores e experi&ecirc;ncias passadas.</span></p>

<p style="text-align:justify"><span style="font-size:16px">O autoconhecimento permite que uma pessoa identifique padr&otilde;es comportamentais, compreenda suas rea&ccedil;&otilde;es diante de desafios e reconhe&ccedil;a sinais precoces de estresse, ansiedade ou depress&atilde;o. Essa conscientiza&ccedil;&atilde;o &eacute; fundamental para a ado&ccedil;&atilde;o de estrat&eacute;gias preventivas e de autocuidado. Quando estamos sintonizados com nossas necessidades emocionais, tornamo-nos mais capazes de tomar decis&otilde;es alinhadas com nossos valores, o que contribui para uma sensa&ccedil;&atilde;o de realiza&ccedil;&atilde;o e prop&oacute;sito.</span></p>

<p style="text-align:justify"><span style="font-size:16px">Al&eacute;m disso, o autoconhecimento facilita a constru&ccedil;&atilde;o de relacionamentos saud&aacute;veis. Ao compreender nossas pr&oacute;prias complexidades, tornamo-nos mais emp&aacute;ticos e compreensivos em rela&ccedil;&atilde;o aos outros. Isso cria conex&otilde;es mais profundas e significativas, promovendo um ambiente social que apoia a sa&uacute;de mental de todos os envolvidos.</span></p>

<p style="text-align:justify"><span style="font-size:16px">Portanto, cultivar o autoconhecimento n&atilde;o &eacute; apenas uma jornada individual, mas tamb&eacute;m um investimento na constru&ccedil;&atilde;o de comunidades mais conscientes e solid&aacute;rias. Ao compreendermos quem somos, podemos criar uma base s&oacute;lida para enfrentar os desafios da vida, promovendo assim uma sa&uacute;de mental robusta e duradoura.</span></p>
'
where id = 1;